### ISSUE TITLE
Add support for states in Date::Holidays::DE

### ISSUE THREAD

**Issue by mario-minati** [jonasbn/perl-date-holidays#31]
### Description

It would be nice if you could add state support from Date::Holidays::DE, similar to Date::Holidays::AU does.

**Comment by jonasbn** [comment]
Hi @mario-minati 

Your request has been implemented in release 1.17, do let me know if you experience any issues, by reporting issue via GitHub. 

Release 1.17 will be uploaded to PAUSE/CPAN today.

Take care and thank you for your contribution :-)

jonasbn

**Comment by mario-minati** [comment]
Thank you very much, that was really a quick fix.

Greets, Mario

**Comment by jonasbn** [comment]
Thanks @mario-minati for raising the issue let me know if you experience any issues.
